/**
 * @fileoverview `recommended` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.js`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';
import type { ESLint, Linter } from 'eslint';

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

export default function recommended(plugin: ESLint.Plugin) {
  return {
    name: 'md/recommended',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    rules: {
      'md/code-lang-shorthand': 'error',
      'md/no-control-character': 'error',
      'md/no-curly-quote': 'error',
      'md/no-double-space': 'error',
      'md/no-git-conflict-marker': 'error',
      'md/no-irregular-dash': 'error',
      'md/no-irregular-whitespace': 'error',
    },
  } as const satisfies Linter.Config;
}
