/**
 * @fileoverview `stylistic` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.js`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';
import type { ESLint, Linter } from 'eslint';

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

export default function stylistic(plugin: ESLint.Plugin) {
  return {
    name: 'md/stylistic',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    rules: {
      'md/consistent-code-style': 'error',
      'md/consistent-delete-style': 'error',
      'md/consistent-emphasis-style': 'error',
      'md/consistent-heading-style': 'error',
      'md/consistent-inline-code-style': 'error',
      'md/consistent-strong-style': 'error',
      'md/consistent-thematic-break-style': 'error',
      'md/consistent-unordered-list-style': 'error',
      'md/no-consecutive-blank-line': 'error',
      'md/no-multiple-atx-heading-space': 'error',
      'md/no-tab': 'error',
      'md/no-trailing-heading-punctuation': 'error',
    },
  } as const satisfies Linter.Config;
}
